### ISSUE TITLE
[Suggestion]: Container fluid, except in widest state

### ISSUE THREAD

**Issue by thomaspink** [ddprrt/griddler#9]
Make container fluid (100% width) except in widest state (fixed width)
#### Benefits:
- **less code**: just a few lines of code. no code in media queries needed
- **better "responsiveness"**: everything resizes smooth and fluid, no jumping when media-queries hit while resizing
#### Possible Implementation:

``` css
.container {
    display: block;
    width: auto; /* or width 100%; */
    max-width: 1200px; /* insert widest state */
    box-sizing: border-box; /* only needed if width: 100% */
    padding-left: $gutter-width;
    padding-right: $gutter-width;
    margin: 0 auto;
}
```

Fixes also issue #8
